### ISSUE TITLE
Make a C.P.F verification in Ruby to verify if the user wrote a valid C.P.F

### ISSUE THREAD

**Issue by adalbertobrant** [adalbertobrant/IRAcoes#19]
Hello, my friends.

Are you enjoying this big party? 

Hacktoberfest is awesome 

In this task you just need to make a CPF verification library, so we could use it in acoes.rb file.

This task need to feel 

- [ ] create a directory called lib
- [ ] create a filename cpf.rb
- [ ] cretea a function verificaCPF(string cpf) which need to return true or false
- [ ] link the cpf.rb lib file to acoes.rb

If you need to know how to understand cpf, this link should be useful to help you, my friend!

[Algorithm to verify CPF](https://dicasdeprogramacao.com.br/algoritmo-para-validar-cpf/)

Have a nice day.

God Bless You All!

**Comment by Aryannath** [comment]
#20  Hi i created a PR
