### ISSUE TITLE
Issue zero - Organizing and sanitizing files 

### ISSUE THREAD

**Issue by adalbertobrant** [adalbertobrant/IRAcoes#2]
Create a new branch named **features** and move to it this files: 

- [ ] acoes.rb.bak-inicial
- [ ] conta.rb
- [ ] menu.rb
- [ ] parser.rb
- [ ] stocks.rb

Create an website directory  structure in the website directory
mkdir website
than all the website directories

Thanks a lot for the help and remember gimme some stars :) 

Happy hacktoberfest 2021 to all my friends. 
God Bless You All.
 Happy hacking.

**Comment by eduardopatrick** [comment]
I opened a PR here for that issue.
