### ISSUE TITLE
Useless assignment to variable - `aux`. File acoes.rb

### ISSUE THREAD

**Issue by adalbertobrant** [adalbertobrant/IRAcoes#3]
Dear First Time User.

File name is **acoes.rb**

 This issue is for you my friend. 

In my code, there is a variable named aux, which is useless in the file named **acoes.rb**.

Your task in this **Important** Mission is to locate the useless variable aux and comment on it.

This issue was made possible by an IA named [DeepSource](https://www.deepsource.io).

That is great.

So the first pull request and all others pointing the line will be valid.

God Bless You All.

Happy Hacktoberfest 2021.

**Comment by manojkrishnak** [comment]
Hi @adalbertobrant, I will take this up and send you a pull request.
