### ISSUE TITLE
Avoid the use of the case equality operator `===`.

### ISSUE THREAD

**Issue by adalbertobrant** [adalbertobrant/IRAcoes#5]
Hello My first-timers Friends in the Hacktoberfest 2021

Filename: **acoes.rb**

This issue was made for you.

In the file named **acoes.rb**, there is a problem about equality operator '==='.

So Your Tasks if accepted are to find and modify it to '=='.

Please this issue is only for First Timers and I have some restricted rules to it, so your repo should not have more than 5 directories to make pull requests in this issue.

All the friend whose find the mistake will be accepted.

You need to assign to this task, to receive your hacktoberfest label.

Happy Hacktoberfest 2021 to All.

God Bless You.

**Comment by manojkrishnak** [comment]
Hi @adalbertobrant can i take this?

**Comment by adalbertobrant** [comment]
> Hi @adalbertobrant can i take this?

Yes my friend. You have 3 days to complete the task.
